- type: job
  parent: CMJobBase
  id: CMRuni
  name: job-name-runi
  description: job-description-runi
  playTimeTracker: CMJobRuni
  icon: "CMJobIconRuni"
  supervisors: job-supervisors-queen
  jobEntity: CMMobRounyXeno
  canBeAntag: false
  accessGroups:
  - CMAccessXeno
