- type: job
  id: CMMaintTech
  name: job-name-shipsengineer
  description: job-description-shipsengineer
  playTimeTracker: JobShipsEngineer
  requirements:
    - !type:RoleTimeRequirement
      role: JobAlfaMarine
      time: 0
    - !type:RoleTimeRequirement
      role: JobDeltaMarine
      time: 0
    - !type:RoleTimeRequirement
      role: JobBravoMarine
      time: 0
    - !type:RoleTimeRequirement
      role: JobCharlieMarine
      time: 0
  startingGear: CMGearMaintTech
  icon: "CMJobIconMaintTech"
  joinNotifyCrew: false
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - MaintTech
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      domestics: 1
      construction: 3
      engineer: 3
      powerLoader: 2

- type: startingGear
  id: ShipsEngineerGear
  equipment:
    head: ClothingHeadHatHardhatYellow
    jumpsuit: ClothingUniformJumpsuitEngineering
    back: ClothingBackpackEngineeringFilled
    shoes: ClothingShoesBootsWork
    outerClothing: ClothingOuterVestHazard
    eyes: ClothingEyesGlassesMeson
    belt: ClothingBeltUtilityEngineering
    ears: ClothingHeadsetEngineering
    id: ShipsEngineerIDCard
    pocket1: EmergencyMedipen
