using Content.Shared._CM14.Mortar;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._CM14.Mortar;

[GenerateTypedNameReferences]
public sealed partial class MortarMenu : DefaultWindow
{
    private MortarBui _owner;

    public MortarMenu(MortarBui owner)
    {
        RobustXamlLoader.Load(this);
        _owner = owner;
    }

    public void UpdateState(MortarBoundUserInterfaceState state)
    {
        CoordsContainer.Children.Clear();

        var i = 0;
        foreach (var savedPoint in state.SavedPoints)
        {
            var control = new MortarCoordsInputControl(i, savedPoint);

            control.Save.OnPressed += _ => _owner.Save(control.Index, control.Coords);
            control.Launch.OnPressed += _ => _owner.Launch(control.Index);

            CoordsContainer.AddChild(control);
            i++;
        }
    }
}
