- type: job
  id: Rigger
  name: job-name-rigger
  description: job-description-rigger
  playTimeTracker: JobRigger
  startingGear: CMGearCargoTech
  icon: "CMJobIconCargoTech"
  joinNotifyCrew: false
  supervisors: job-supervisors-supply-officer
  canBeAntag: false
  accessGroups:
  - CMCargoTech
  special:
  - !type:AddComponentSpecial
    components:
    - type: JobRank
      job: Rigger
    - type: Skills
      construction: 1
      powerLoader: 2

- type: startingGear
  id: CMGearCargoTech
  equipment:
    jumpsuit: CMJumpsuitCargoTech
    back: CMSatchelMarineTech
    shoes: CMBootsBlack
    head: CMHeadCapCargo
    gloves: CMHandsInsulated
    id: CMIDCardCargoTech
    ears: CMHeadsetRequisition
    pocket1: CMPouchGeneralMedium
#    belt: TODO CM14 M276 Pattern General Pistol Holster Rig Filled
