- type: job
  id: CMRigger
  name: job-name-rigger
  description: job-description-rigger
  playTimeTracker: CMJobRigger
  startingGear: CMGearCargoTech
  icon: "CMJobIconCargoTech"
  supervisors: job-supervisors-staff-officer
  joinNotifyCrew: false
  canBeAntag: false
  accessGroups:
  - CMCargoTech
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      construction: 1
      powerLoader: 2

- type: startingGear
  id: CMGearCargoTech
  equipment:
    jumpsuit: CMJumpsuitCryo
    ears: CMHeadsetRequisition
    id: CMIDCardCargoTech
