- type: job
  id: AlfaMarine
  name: job-name-alfa-marine
  description: job-description-alfamarine
  playTimeTracker: JobAlfaMarine
  startingGear: CMGearRifleman
  icon: "JobIconAlfaMarine"
  joinNotifyCrew: false
  supervisors: job-supervisors-commander
  canBeAntag: false
  accessGroups:
  - Rifleman
  special:
  - !type:AddComponentSpecial
    components:
    - type: JobRank
      job: AlfaMarine
    - type: Skills
  hasIcon: false

- type: startingGear
  id: CMGearRifleman
  equipment:
    jumpsuit: JumpsuitMarine # TODO CM14 all squad roles should spawn with no jumpsuit but still have clothes on
    back: CMSatchelMarine
    id: CMDogtagRifleman

- type: startingGear
  id: CMGearRiflemanEquipped
  equipment:
    jumpsuit: JumpsuitMarine
    back: CMSatchelMarine
    shoes: CMBootsBlackFilled
    head: ArmorHelmetM10
    outerClothing: CMArmorM3Medium
    gloves: CMHandsBlackMarine
    id: CMDogtagRifleman
    ears: CMHeadsetAlpha
