- type: job
  id: AlfaSpecialist
  name: job-name-alfa-specialist
  description: job-description-alfaspecialist
  playTimeTracker: JobAlfaSpecialist
  requirements:
    - !type:DepartmentTimeRequirement
      department: MarinesGarrison
      time: 54000 # 15 hrs
  startingGear: CMGearWeaponsSpecialist
  icon: "JobIconAlfaSpecialist"
  joinNotifyCrew: false
  supervisors: job-supervisors-commander
  canBeAntag: false
  accessGroups:
  - WeaponSpec
  special:
  - !type:AddComponentSpecial
    components:
    - type: JobRank
      job: AlfaSpecialist
    - type: Skills
      cqc: 1
      construction: 1
      endurance: 2
      engineer: 1
      jtac: 1
      meleeWeapons: 1
      specialistWeapons: 1

- type: startingGear
  id: CMGearWeaponsSpecialist
  equipment:
    jumpsuit: JumpsuitMarine # TODO CM14 all squad roles should spawn with no jumpsuit but still have clothes on
    back: CMSatchelMarine
    id: CMDogtagWeaponsSpecialist

- type: startingGear
  id: CMGearWeaponsSpecialistEquipped
  equipment:
    jumpsuit: JumpsuitMarine
    back: CMSatchelMarine
    shoes: CMBootsBlackFilled
    head: ArmorHelmetM10
    outerClothing: CMArmorM3Medium
    gloves: CMHandsBlackMarine
    id: CMDogtagWeaponsSpecialist
    ears: CMHeadsetAlpha
