- type: job
  id: MilitaryPoliceOfficer
  name: job-name-militarypoliceofficer
  description: job-description-militarypoliceofficer
  playTimeTracker: JobMilitaryPoliceOfficer
  requirements:
    - !type:DepartmentTimeRequirement
      department: MilitaryPolice
      time: 36000 # 10 hrs
  weight: 5
  startingGear: CMGearChiefMP
  icon: "CMJobIconChiefMP"
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: job-supervisors-staff-officer
  canBeAntag: false
  accessGroups:
  - CMP
  special:
  - !type:AddComponentSpecial
    components:
    - type: JobRank
      job: MilitaryPoliceOfficer
    - type: Skills
      construction: 2
      cqc: 2
      endurance: 2
      engineer: 2
      fireman: 2
      intel: 1
      jtac: 3
      leadership: 2
      medical: 1
      meleeWeapons: 1
      overwatch: 1
      police: 2
    - type: MarineOrders

- type: startingGear
  id: MilitaryPoliceOfficerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitMilitaryPoliceOfficer
    back: ClothingBackpackHOSFilled
    shoes: ClothingShoesBootsJackSec # Corvax-Resprite
    outerClothing: ClothingOuterCoatHoSTrench
    eyes: ClothingEyesGlassesSecurity
    head: ClothingHeadHatBeretHoS
    gloves: ClothingHandsGlovesCombat
    id: PoliceOfficerIDCard
    ears: ClothingHeadsetSecurity
    pocket1: EmergencyMedipen
