- type: job
  id: BravoEngineer
  name: job-name-bravo-engineer
  description: job-description-bravoengineer
  playTimeTracker: JobBravoEngineer
  requirements:
    - !type:RoleTimeRequirement
      role: JobShipsEngineer
      time: 10800 # 3 hrs
  startingGear: CMGearCombatTech
  icon: "JobIconBravoEngineer"
  joinNotifyCrew: false
  supervisors: job-supervisors-commander
  canBeAntag: false
  accessGroups:
  - CombatTech
  special:
  - !type:AddComponentSpecial
    components:
    - type: JobRank
      job: BravoEngineer
    - type: Skills
      constructiopn: 2
      engineer: 2
      jtac: 1
      vehicle: 1
