using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._CM14.Xeno.UI;

[GenerateTypedNameReferences]
public sealed partial class XenoEvolutionControl : Control
{
    public XenoEvolutionControl(string name, string description, string price, bool canBuy, Texture? texture = null)
    {
        RobustXamlLoader.Load(this);

        Name.Text = name;
        Description.SetMessage(description);

        BuyButton.Text = price;
        BuyButton.Disabled = !canBuy;

        Icon.Texture = texture;
    }
}
