- type: job
  id: CharlieEngineer
  name: job-name-charlie-engineer
  description: job-description-charlieengineer
  playTimeTracker: JobCharlieEngineer
  requirements:
    - !type:RoleTimeRequirement
      role: JobShipsEngineer
      time: 10800 # 3 hrs
  startingGear: CMGearCombatTech
  icon: "JobIconCharlieEngineer"
  joinNotifyCrew: false
  supervisors: job-supervisors-commander
  canBeAntag: false
  accessGroups:
  - CombatTech
  special:
  - !type:AddComponentSpecial
    components:
    - type: JobRank
      job: CharlieEngineer
    - type: Skills
      constructiopn: 2
      engineer: 2
      jtac: 1
      vehicle: 1
