- type: job
  id: CharlieSpecialist
  name: job-name-charlie-specialist
  description: job-description-charliespecialist
  playTimeTracker: JobCharlieSpecialist
  requirements:
    - !type:DepartmentTimeRequirement
      department: MarinesGarrison
      time: 54000 # 15 hrs
  startingGear: CMGearWeaponsSpecialist
  icon: "JobIconCharlieSpecialist"
  joinNotifyCrew: false
  supervisors: job-supervisors-commander
  canBeAntag: false
  accessGroups:
  - WeaponSpec
  special:
  - !type:AddComponentSpecial
    components:
    - type: JobRank
      job: CharlieSpecialist
    - type: Skills
      cqc: 1
      construction: 1
      endurance: 2
      engineer: 1
      jtac: 1
      meleeWeapons: 1
      specialistWeapons: 1
