- type: job
  id: CharlieMedic
  name: job-name-charlie-medic
  description: job-description-charliemedic
  playTimeTracker: JobCharlieMedic
  requirements:
    - !type:RoleTimeRequirement
      role: JobMilitaryMedic
      time: 10800 # 3 hrs
  startingGear: CMGearHospitalCorpsman
  icon: "JobIconCharlieMedic"
  joinNotifyCrew: false
  supervisors: job-supervisors-commander
  canBeAntag: false
  accessGroups:
  - HospitalCorpsman
  special:
  - !type:AddComponentSpecial
    components:
    - type: JobRank
      job: CharlieMedic
    - type: Skills
      jtac: 1
      medical: 2
      surgery: 1
