- type: job
  parent: CMJobBase
  id: CMFieldCommander
  name: job-name-fieldcommander
  description: job-description-fieldcommander
  playTimeTracker: CMJobFieldCommander
  weight: 10
  startingGear: CMGearFieldCommander
  icon: "CMJobIconFieldCommander"
  supervisors: job-supervisors-head-operations
  canBeAntag: false
  accessGroups:
  - CMMarineMain
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      cqc: 2
      construction: 2
      fireman: 2
      endurance: 2
      engineer: 2
      execution: 1
      intel: 2
      jtac: 4
      leadership: 3
      medical: 3
      navigations: 1
      overwatch: 1
      police: 2
      powerLoader: 2
      smartgun: 1
      surgery: 1
      vehicles: 1
    - type: MarineOrders

- type: startingGear
  id: CMGearFieldCommander
  equipment:
    jumpsuit: CMJumpsuitCO
    back: CMSatchelGeneral
    shoes: ClothingShoesBootsLaceup
    ears: CMHeadsetFieldCommand
