- type: job
  id: FieldCommander
  name: job-name-fieldcommander
  description: job-description-fieldcommander
  playTimeTracker: JobFieldCommander
  requirements:
  - !type:DepartmentTimeRequirement
    department: CMCommand
    time: 36000 # 10 hours
  weight: 10
  startingGear: CMGearCommandingOfficer
  icon: "CMJobIconCommandingOfficer"
  supervisors: job-supervisors-head-operations
  canBeAntag: false
  accessGroups:
  - ShipMasterAccess
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      cqc: 2
      construction: 2
      fireman: 2
      endurance: 2
      engineer: 2
      execution: 1
      intel: 2
      jtac: 4
      leadership: 3
      medical: 3
      navigations: 1
      overwatch: 1
      police: 2
      powerLoader: 2
      smartgun: 1
      surgery: 1
      vehicles: 1
    - type: MarineOrders

- type: startingGear
  id: CMGearCommandingOfficer
  equipment:
    jumpsuit: CMJumpsuitCO
    back: CMSatchel
    shoes: CMShoesLaceupCommander
    head: CMHeadBeretCO
    outerClothing: CMCoatOfficer
    id: CMIDCardCommandingOfficer
    ears: CMHeadsetSeniorCommand
