- type: job
  id: HeadOperations
  name: job-name-headoperations
  description: job-description-headoperations
  playTimeTracker: JobHeadOperations
  requirements:
  - !type:RoleTimeRequirement
    role: JobStaffOfficer
    time: 10800 # 3 hrs
  weight: 5
  startingGear: CMGearStaffOfficer
  icon: "CMJobIconExecutiveOfficer"
  supervisors: job-supervisors-uge
  canBeAntag: false
  accessGroups:
  - MarineMain
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      cqc: 2
      construction: 2
      endurance: 2
      engineer: 2
      fireman: 2
      intel: 2
      jtac: 4
      leadership: 3
      medical: 3
      navigations: 1
      overwatch: 1
      police: 1
      powerLoader: 2
      surgery: 1
      vehicles: 1
    - type: MarineOrders

- type: startingGear
  id: CMGearExecutiveOfficer
  equipment:
    jumpsuit: CMJumpsuitBO
    back: CMSatchel
    shoes: CMShoesLaceup
    head: CMHeadCap
    outerClothing: CMCoatOfficer
    id: CMIDCardExecutiveOfficer
    ears: CMHeadsetLeader
