- type: job
  parent: CMJobBase
  id: CMHeadOperations
  name: job-name-headoperations
  description: job-description-headoperations
  playTimeTracker: CMJobHeadOperations
  startingGear: CMGearHeadOperations
  icon: "CMJobIconHeadOperations"
  supervisors: job-supervisors-uge
  canBeAntag: false
  accessGroups:
  - CMShipMasterAccess
  - CMMarineMain
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      cqc: 2
      construction: 2
      endurance: 2
      engineer: 2
      fireman: 2
      intel: 2
      jtac: 4
      leadership: 3
      medical: 3
      navigations: 1
      overwatch: 1
      police: 1
      powerLoader: 2
      surgery: 1
      vehicles: 1
    - type: MarineOrders

- type: startingGear
  id: CMGearHeadOperations
  equipment:
    jumpsuit: CMJumpsuitCO
    back: CMSatchelGeneral
    shoes: ClothingShoesBootsLaceup
    ears: CMHeadsetSeniorCommand
    id: CMIDCardHeadOperations

