- type: job
  parent: CMJobBase
  id: CMStaffOfficer
  name: job-name-staffofficer
  description: job-description-staffofficer
  playTimeTracker: CMJobStaffOfficer
  startingGear: CMGearStaffOfficer
  icon: "CMJobIconStaffOfficer"
  supervisors: job-supervisors-head-operations
  canBeAntag: false
  accessGroups:
  - CMShipMasterAccess
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      construction: 2
      engineer: 2
      fireman: 1
      intel: 1
      jtac: 3
      leadership: 2
      medical: 2
      overwatch: 1
      police: 1
      powerLoader: 1
      vehicles: 1
    - type: MarineOrders

- type: startingGear
  id: CMGearStaffOfficer
  equipment:
    jumpsuit: CMJumpsuitCO
    back: CMSatchelGeneral
    shoes: ClothingShoesBootsLaceup
    ears: CMHeadsetStaffOfficer
    id: CMIDCardStaffOfficer
