using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._CM14.Surgery;

[GenerateTypedNameReferences]
public sealed partial class CMSurgeryWindow : DefaultWindow
{
    public CMSurgeryWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
