- type: job
  id: CMPilotDropship
  name: job-name-pilotdropship
  description: job-description-pilotdropship
  playTimeTracker: CMJobPilotDropship
  startingGear: CMGearPilotDropship
  icon: "CMJobIconPilotDropship"
  supervisors: job-supervisors-staff-officer
  canBeAntag: false
  access:
  - CMShipPilot
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      intel: 1
      jtac: 2
      leadership: 1
      medical: 2
      overwatch: 1
      pilot: 2
      powerLoader: 2
      surgery: 1

- type: startingGear
  id: CMGearPilotDropship
  equipment:
    jumpsuit: CMJumpsuitCryo
    ears: CMHeadsetJTAC
    id: CMIDCardPilotDropship
