- type: entity
  id: CMDepartmentsHuman
  categories:
  - hideSpawnMenu
  components:
  - type: DepartmentGroup
    name: role-timer-human-roles
    color: White
    departments:
    - CMAuxiliarySupport
    - CMCommand
    - CMEngineering
    - CMSquad
    - CMMedbay
    - CMMilitaryPolice
    - CMOther
    - CMRequisitions
    - CMSurvivor

- type: entity
  id: CMJobsMedical
  categories:
  - hideSpawnMenu
  components:
  - type: JobGroup
    name: role-timer-medical-roles
    color: "#008160"
    jobs:
    # - CMHospitalCorpsman
    # - CMCMO
    - CMDoctor
    # - CMNurse
    - CMResearcher

- type: entity
  id: CMJobsEngineering
  categories:
  - hideSpawnMenu
  components:
  - type: JobGroup
    name: role-timer-engineering-roles
    color: "#A66300"
    jobs:
    # - CMCombatTech
    # - CMChiefEngineer
    # - CMOrdnanceTech
    - CMMaintTech

- type: entity
  id: CMJobsDropship
  categories:
  - hideSpawnMenu
  components:
  - type: JobGroup
    name: role-timer-dropship-roles
    color: "#C38312"
    jobs:
    # - CMDropshipCrewChief
    - CMPilotDropship
    - CMPilotGunship
